[package]
name = "filters"
version = "0.1.0"
authors = ["Jason Miller <contact@jasonmiller.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
approx = "0.3.2"
ndarray = "0.13.1"
itertools = "0.9.0"
wgpu = "0.5.0"

[dev-dependencies]
image = "0.23.4"

